version: '3.5'
services:
  sensors-reader:
    container_name: sensors-reader
    image: davidleonm/weather-station-sensors-reader
    privileged: true
    restart: unless-stopped
    environment:
      - LOGGING_LEVEL=ERROR
      - BME_280_SENSOR_ENABLED=true
      - GROUND_SENSOR_ENABLED=true
      - WIND_SENSOR_ENABLED=true
      - RAINFALL_SENSOR_ENABLED=true
      - ANEMOMETER_PORT_NUMBER=22
      - RAIN_GAUGE_PORT_NUMBER=XX
      - SERVER=127.0.0.1
      - DATABASE=my_db
      - USER=my_user
      - PASSWORD=my_password
    volumes:
    - '/etc/timezone:/etc/timezone:ro'
    - '/etc/localtime:/etc/localtime:ro'